name = "envgateway"
main = "src/index.js"
compatibility_date = "2024-05-01"

[env.vars]
WORKER_VERSION = "1.0.0"
WRK_ROUTES = '''
{
  "/koodo-reader/": "https://koodo-reader-sever.19820805.xyz",
  "/blog/": "https://blog.fengmayou.top"
}
'''